name: Cypress Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [assigned, opened, synchronize, reopened]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          # Linux and MacOS
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_APP_API_BASE_URL: https://hn.algolia.com/api/v1
